Update sv_bennys to support qb-management exports
qbcore-framework/qb-customs pull request #69
Opened 2022-02-22 14:46 UTC by ARSSANTO

2022-02-22 19:54 UTC, mk3ext requested changes
The management still creates the functions and callbacks under bossmenu, so this is unneeded
See https://github.com/qbcore-framework/qb-management/blob/main/server/sv_boss.lua#L87

2022-02-22 20:45 UTC, ARSSANTO commented
is that boss menu will be a thing in next days ?

2022-03-09 20:22 UTC, ItsANoBrainer commented
> The management still creates the functions and callbacks under bossmenu, so this is unneeded See https://github.com/qbcore-framework/qb-management/blob/main/server/sv_boss.lua#L87

Export name is based on resource name, not file name.

2022-03-09 20:22 UTC, ItsANoBrainer approved these changes

2022-04-07 01:43 UTC, closed without merging