Added option to Percentage price scale
qbcore-framework/qb-customs pull request #77
Opened 2022-03-28 06:59 UTC by Rav3n95

2022-04-07 01:50 UTC, GhzGarage commented
I'll leave this to you @ItsANoBrainer so you can decide. it has conflicts anyway

2022-04-20 23:38 UTC, ItsANoBrainer requested changes
Left an example of a cleaner version of doing the Config price. If you can change all the entries to a version like that, and also remove the default changes to shared/locations.lua, I approve! Also need conflicts fixed.

2022-04-20 23:38 UTC, ItsANoBrainer commented on client/cl_ui.lua
> +                        end
```suggestion
local price = Config.UsePercentage and math.floor((vehiclePrice / 100) * vehicleCustomisationPricesPercentage.performance[tempNum]) or vehicleCustomisationPrices.performance.prices[tempNum]
populateMenu(v.category:gsub("%s+", "") .. "Menu", n.id, n.name, "$" ..price )
```
If you could make this change to all the entries to make it "cleaner" looking.

2022-04-22 20:04 UTC, ItsANoBrainer requested changes

2022-04-22 20:04 UTC, ItsANoBrainer commented on config.lua
> +    performance = {0, 3, 6, 9, 12, 15},
```suggestion
    performance = {0, 3, 6, 9, 12, 15, 20},
```

2022-04-22 20:25 UTC, Rav3n95 commented
Sorry i been a bit busy whit qb-garages polyzone rework. Soonest i done whit that, i be ready to rework this to new version. Also thanks a lot for helping out.

2022-04-23 10:43 UTC, Rav3n95 commented
Updated, tested only alone.

2022-05-03 17:27 UTC, uShifty requested changes

2022-05-03 17:27 UTC, uShifty commented on client/cl_bennys.lua
> +    for k, v in pairs(QBCore.Shared.Vehicles) do
Replace tis loop with this 
`local hash = GetEntityModel(vehicle)`
`vehiclePrice = QBShared.VehicleHashes[hash] and QBShared.VehicleHashes[hash].price or vehicleBasePrice`

2022-05-05 16:48 UTC, Rav3n95 commented on client/cl_bennys.lua
> +    for k, v in pairs(QBCore.Shared.Vehicles) do
Thanks

2022-12-09 20:03 UTC, Z3rio commented
Not needed PR considering we are going to rewrite qb-customs anyways.

2022-12-09 20:03 UTC, closed without merging